### ISSUE TITLE
Bobbles and key bind broken

### ISSUE THREAD

**Issue by jakeoakes** [ofek2608/crafting_on_a_stick#12]
The stick dose not go into the slot and there isnt a option to add a key bind

V - 1.21.0.0

Using ATM10 Pre Beta

**Comment by ofek2608** [comment]
As the patch notes says, I have removed the support for Curios temporarily since they haven't updated yet.
Which mod are you using instead of curios? or do you have an early access for it?

**Comment by ofek2608** [comment]
I added support for Adorned

**Comment by jakeoakes** [comment]
Yeah thats whats currenlty being used!
