### ISSUE TITLE
[1.21] Crash on startup

### ISSUE THREAD

**Issue by NielsPilgaard** [ofek2608/crafting_on_a_stick#13]
\o

I currently crash on startup, COAS seems to be involved.

- crafting_on_a_stick-1.21.0.1
- curios-neoforge-9.0.4+1.21
- neoforge-21.0.53

https://gist.github.com/NielsPilgaard/f348cf25c4d04f25c25561b813bf7359

**Comment by NielsPilgaard** [comment]
Turns out this was caused by another mod, sorry! :)

Edit: I was wrong, this crash was because I used Curios API Continuation instead of Adorned.

**Comment by ofek2608** [comment]
This mod uses Adorned by LobsterJonn and not Curios API Continuation by SSKirillSS
https://www.curseforge.com/minecraft/mc-mods/adorned

**Comment by NielsPilgaard** [comment]
> This mod uses Adorned by LobsterJonn and not Curios API Continuation by SSKirillSS https://www.curseforge.com/minecraft/mc-mods/adorned

I see, thank you 👍 
I have other mods that depend on Curios API Continuation unfortunately.

**Comment by kreezxil** [comment]
weird, i installed this mod but curseforge app pulled in the curios continuation api, is the mod tagged properly for its dependencies on curseforge?
