### ISSUE TITLE
crash while tryinbg to rename stick on server

### ISSUE THREAD

**Issue by thebikwirm** [ofek2608/crafting_on_a_stick#3]
16.5 
forge 36.2.39
crafting on stick version 1.0.2

crash report included
[crash-2023-09-13_13.39.52-server.txt](https://github.com/ofek2608/crafting_on_a_stick/files/12593820/crash-2023-09-13_13.39.52-server.txt)

**Comment by ofek2608** [comment]
Thanks for the report, sorry, i am not going to fix it as it's an old version.
