### ISSUE TITLE
Request: Backport Curios integration

### ISSUE THREAD

**Issue by IZeeLikeEyeZee** [ofek2608/crafting_on_a_stick#5]
I'm using this mod on 1.16.5 and the curios integration would be super useful! I'll probably just create a server-side config for it for now but idk how well that's going to work, I'll share it if/when I do though 👍

**Comment by IZeeLikeEyeZee** [comment]
Realized this doesn't implement the hotkey and idk if you can even do that with a datapack lol...

<s>Here it is in case it helps anyone

Pack:
_install on the client as a resource pack, and on the server as a datapack_
[Curios on a stick.zip](https://github.com/ofek2608/crafting_on_a_stick/files/12874333/Curios.on.a.stick.zip)

Server Config:
_Add the following to your curios-server.toml (located at /world/serverconfig)_
```
[[curiosSettings]]
	identifier = "craftingstick"
	visible = true
	size = 1
	icon = "curios:slot/craftingstick"
``` 
</s>

**Comment by ofek2608** [comment]
I am sorry, i won't add this.
