### ISSUE TITLE
[request] modrinth 1.19.2 forge release

### ISSUE THREAD

**Issue by Yarden-zamir** [ofek2608/crafting_on_a_stick#6]
Would love to have one! We really like your mod

**Comment by ofek2608** [comment]
I have made it, it may take time to show since it's a new project.
https://modrinth.com/mod/crafting-on-a-stick/moderation

**Comment by Yarden-zamir** [comment]
Awesome! Thank you!

**Comment by Yarden-zamir** [comment]
um... might sound like a weird request but can you upload the same version to curse forge? My modpack is on both and the version you pushed to mr is 1.1.2 while the cf one is 1.0.5
