### ISSUE TITLE
[request] up to date forge release for 1.19.2 on curse forge

### ISSUE THREAD

**Issue by Yarden-zamir** [ofek2608/crafting_on_a_stick#7]
I know I just asked for the "opposite" but can you upload the same version to curse forge? My modpack is on both and the version you pushed to mr is 1.1.2 while the cf one is 1.0.5. Leading to incompatible clients. Thank! Sorry for the issue spam 😅

**Comment by ofek2608** [comment]
I uploaded both the 1.0.5 version to modrinth and all 1.1.x versions to curseforge.
I bumped the versions up since they had a mess from the backporting (they are basically identical) sorry for the inconvenience.

**Comment by Yarden-zamir** [comment]
Thank you! You are awesome!
